<?php

/**
 * @file
 * Module for building and managing site's blocks.
 */


module_load_include('inc', 'gv_blocks', 'inc/constants');


/**
 * Implements hook_block_info().
 */
function gv_blocks_block_info() {
  $blocks['main_menu_om_news'] = array(
    'info' => t('OM News'), 
    'cache' => DRUPAL_NO_CACHE, // DRUPAL_CACHE_GLOBAL
  );
  $blocks['main_menu_om_providers'] = array(
    'info' => t('OM Providers'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['main_menu_om_blog'] = array(
    'info' => t('OM Blog'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['main_menu_om_aboutus'] = array(
    'info' => t('OM About Us'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['main_menu_om_allaboutvoip'] = array(
    'info' => t('OM All About VoIP'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['main_menu_om_editor'] = array(
    'info' => t('OM Editor'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['main_menu_om_user'] = array(
    'info' => t('OM User'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  
  $blocks['footer_menu'] = array(
    'info' => t('Footer menu'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['header_links'] = array(
    'info' => t('Header links'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['request_quote'] = array(
    'info' => t('Request a quote'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['get_access_banner'] = array(
    'info' => t('Get access... Banner'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  // Topics block for different content types.
  $content_types = array('blog_post' => 'blog', 'news_post' => 'news', 'article' => 'articles');
  foreach ($content_types as $content_type => $label) {
    
    $blocks[$content_type . '_topics'] = array(
      'info' => t(drupal_ucfirst($label) . ' topics'),
      'cache' => DRUPAL_NO_CACHE,
    );
  }
  
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function gv_blocks_block_view($delta = '') {
  $block = array();
  switch ($delta) {      
    case 'main_menu_om_news':
      $block['subject'] = t('OM News');
      $block['content'] = gv_blocks_get_omMenuBlock_byTitle('News', 'gv_blocks_get_omMenuBlock_News');
      break;
    case 'main_menu_om_providers':
      $block['subject'] = t('OM Providers');
      $block['content'] = gv_blocks_get_omMenuBlock_byTitle('VoIP Providers', 'gv_blocks_get_omMenuBlock_Providers');
      break;
    case 'main_menu_om_blog':
      $block['subject'] = t('OM Blog');
      $block['content'] = gv_blocks_get_omMenuBlock_byTitle('VoIP Blog', 'gv_blocks_get_omMenuBlock_Blog');
      break;
    case 'main_menu_om_aboutus':
      $block['subject'] = t('OM About Us');
      $block['content'] = gv_blocks_get_omMenuBlock_byTitle('About Us', 'gv_blocks_get_omMenuBlock_AboutUs');
      break;
    case 'main_menu_om_allaboutvoip':
      $block['subject'] = t('OM All About VoIP');
      $block['content'] = gv_blocks_get_omMenuBlock_byTitle('All About VoIP', 'gv_blocks_get_omMenuBlock_AllAboutVoIP');
      break;
    case 'main_menu_om_editor':
      $block['subject'] = t('OM Editor');
      $block['content'] = gv_blocks_get_omMenuBlock_byTitle('Editor', 'gv_blocks_get_omMenuBlock_Editor');
      break;     
    case 'main_menu_om_user':
      $block['subject'] = t('OM User');
      $block['content'] = gv_blocks_get_omMenuBlock_byTitle('User', 'gv_blocks_get_omMenuBlock_User');
      break; 
    
    case 'footer_menu':
      $block['subject'] = t('Footer menu');
      $block['content'] = gv_blocks_get_footerMenu();
      break; 
    case 'header_links':
      $block['subject'] = t('Header links');
      $block['content'] = gv_blocks_get_headerLinks();
      break; 
    case 'request_quote':
      $block['subject'] = t('Request a quote');
      $block['content'] = gv_blocks_get_requestQuote();
      break; 
    case 'get_access_banner':
      $block['subject'] = t('GET ACCESS TO THE LARGEST <br>VOIP FOOTPRINT <br>IN THE NATION');
      $block['content'] = gv_blocks_get_accessToFootprintBanner();
      break;         
        
    default:
      // Get blocks for topics for a specific content type.
      if (strpos($delta, '_topics')) {
        $content_types = array('blog_post' => 'blog', 'news_post' => 'news', 'article' => 'articles');
        $content_type = str_replace('_topics', '', $delta);
        if(!isset($content_types[$content_type])) {
          continue;
        }
        $block['subject'] = t(drupal_ucfirst($content_types[$content_type]) . ' topics');
        $block['content'] = gv_blocks_get_topicsBlock($content_type);
      }
      break;
  }

  return $block;
}


/**
 * Returns a themed topics block for a specific content type.
 * 
 * Allows to use same topics for News, Articles, Blog posts, etc.
 */
function gv_blocks_get_topicsBlock($content_type) {
  
  global $language;
  $topics = NULL;
  $topics = cache_get($content_type . '_topics_block' . $language->language);
  if (!$topics || empty($topics->data) || $topics->expire < time()) {
    // Key = url_argument, used in building the url, 
    // for example,
    // topics/news for topics list for news 
    // OR blog/provider for show all blog posts tagged with 'provider' topic.
    $content_types = array('blog_post' => 'blog', 'news_post' => 'news', 'article' => 'articles');
    $url_argument = $content_types[$content_type];
    $topics = gv_misc_getTopics($content_type, $url_argument, 2);
    if(!$topics) {
      return NULL;
    }
    $topics = theme('gv_misc_submenuSimple', array('submenu' => array('below' => $topics), 'class' => 'topics'));
    $topics .= '<div class="more-link">' . l(t('More'), $url_argument . '/tags') . '</div>';
    // Expire = current time + 4 hours.
    cache_set($content_type . '_topics_block' . $language->language, $topics, 'cache', time() + 14400);
  }
  else {
    $topics = $topics->data;
  }
  return $topics; 
}


/**
 * Returns a themed News topics block. 
 * 
 * Allows to use same topics for News, Articles, Blog posts, etc.
 */
/*
function gv_blocks_get_newsTopics() {
  global $language;
  $topics = cache_get('news_topics_block' . $language->language);
  if (!$topics || empty($topics->data) || $topics->expire < time()) {
    $topics = gv_misc_getTopics('news_post', 'news', 2);
    $topics = theme('gv_misc_submenuSimple', array('submenu' => array('below' => $topics), 'class' => 'topics'));
    $topics .= '<div class="more-link">' . l(t('More'), 'news-topics'). '</div>';
    // Expire = current time + 4 hours.
    cache_set('news_topics_block' . $language->language, $topics, 'cache', time() + 14400);
  }
  else {
    $topics = $topics->data;
  }
  return $topics; 
}
*/


/**
 * Returns a themed Header links block.
 */
function gv_blocks_get_headerLinks() {
  $menu = menu_build_tree('menu-header-links');
  //return '<span class="menu-preface">Header:</span>' . theme('gv_misc_submenuSimple', array('submenu' => array('below' => $menu), 'class' => 'menu'));
  return theme('gv_misc_headerLinks', array('submenu' => array('below' => $menu)));
}


/**
 * Returns a themed Footer menu.
 */
function gv_blocks_get_footerMenu() {
  $menu = menu_build_tree('menu-footer-menu');
  return theme('gv_misc_submenuSimple', array('submenu' => array('below' => $menu), 'class' => 'menu', 'delimiter' => '<li> | </li>'));
  // . '<div class="c">© 2012 GetVoIP.com | All Rights Reserved</div>';
}


/**
 * Dispatcher for getting themed block for MegaMenu by a block title.
 */
function gv_blocks_get_omMenuBlock_byTitle($title, $function) {

  // global $language;
  // $types = cache_get('types_' . $language->language);
  // Expire = current time + 2 hours.
  // cache_set('types_' . $language->language, $types, 'cache', time() + 7200);
  
  // Get main menu wireframe menu.
  $submenu = gv_blocks_getSubmenuByTitle('main-menu', $title);
  //return '<div class="om-btitle">' . $title . '</div>' . $function($submenu);
  return $function($submenu);
}


/**
 * Returns a themed News block content for MegaMenu.
 */
function gv_blocks_get_omMenuBlock_News($submenu) {
  $block_data = array('module' => 'gv_blocks', 'delta' => 'news_post_topics', 'subject_visible' => FALSE);
  $out = gv_blocks_getBlockThemed($block_data);
  return $out;  
  //return theme('gv_misc_submenuSimple', array('submenu' => $submenu, 'class' => 'block'));
}


/**
 * Returns a themed VoIP Providers block content for MegaMenu.
 */
function gv_blocks_get_omMenuBlock_Providers($submenu) {
  return theme('gv_misc_submenuSimple', array('submenu' => $submenu, 'class' => 'block'));
}


/**
 * Returns a themed VoIP Blog block content for MegaMenu.
 */
function gv_blocks_get_omMenuBlock_Blog($submenu) {
  $block_data = array('module' => 'gv_blocks', 'delta' => 'blog_post_topics', 'subject_visible' => FALSE);
  $out = gv_blocks_getBlockThemed($block_data);
  return $out;  
  //return theme('gv_misc_submenuSimple', array('submenu' => $submenu, 'class' => 'block'));
}


/**
 * Returns a themed VoIP Blog block content for MegaMenu.
 */
function gv_blocks_get_omMenuBlock_AboutUs($submenu) {
  return theme('gv_misc_submenuSimple', array('submenu' => $submenu, 'class' => 'block'));
}


/**
 * Returns a themed All About VoIP block content for MegaMenu.
 */
function gv_blocks_get_omMenuBlock_AllAboutVoIP($submenu) {
  $block_data = array('module' => 'gv_blocks', 'delta' => 'article_topics', 'subject_visible' => FALSE);
  $out = gv_blocks_getBlockThemed($block_data);
  return $out;   
  //return theme('gv_misc_submenuSimple', array('submenu' => $submenu, 'class' => 'block'));
}


/**
 * Returns a themed Editor block content for MegaMenu.
 */
function gv_blocks_get_omMenuBlock_Editor($submenu) {
  return theme('gv_misc_submenuSimple', array('submenu' => $submenu, 'class' => 'block'));
}


/**
 * Returns a themed custiom User block content (which contains several blocks and contents) for MegaMenu.
 */
function gv_blocks_get_omMenuBlock_User($submenu) {
  
  $out = NULL;
  // Build block for User login/logout.
  global $user;
  if($user->uid) {
    $out .= '<div class="title">' . t('You are logged in as ') . '<b>' . $user->name . '</b></div>';
    
    $block_data = array('module' => 'system', 'delta' => 'user-menu', 'subject_visible' => FALSE);
    $out .= gv_blocks_getBlockThemed($block_data);
  }
  else {
    $block_data = array('module' => 'user', 'delta' => 'login');
    $out .= gv_blocks_getBlockThemed($block_data);
  }
  return $out; 
}


/**
 * Returns a submenu from a menu.
 */
function gv_blocks_getSubmenuByTitle($menu_name, $submenu_title) {
  $menu = menu_build_tree($menu_name);
  if(!$menu) {
    return NULL;
  }
  foreach ($menu as $submenu) {
    if ($submenu['link']['link_title'] == $submenu_title) {
      return $submenu;
    }
  }
  return NULL;
}


/**
 * Wrap a block content in proper block's divs.
 */
function gv_blocks_wrapInBlockThemed($block_data, $block)
{
  if(!isset($block['content']) || !$block['content']) {
      return null;
  }
  if (is_array($block['content'])) {
    $block['content'] = render($block);
  }
  
  if (isset($block_data['shadow']) && $block_data['shadow']) {
    return 
      '<section id="block-' . $block_data['module'] . '-' . $block_data['delta'] . '" class="block gv block-' . $block_data['module'] . '">' 
        . '<div class="inside">'
            . ( ($block['subject'] && (!isset($block_data['subject_visible']) || $block_data['subject_visible']) )
                ? 
                '<div class="block-icon pngfix"></div><h2 class="block-title">' . $block['subject'] . '</h2>'
                :
                '') 
            . '<div class="content">' . $block['content'] . '</div>
          </div> <!-- /.inside -->
          <div class="shadow"></div>
      </section>';
  }
  else {
    return 
      '<section id="block-' . $block_data['module'] . '-' . $block_data['delta'] . '" class="block gv block-' . $block_data['module'] . '">' 
         . ( ($block['subject'] && (!isset($block_data['subject_visible']) || $block_data['subject_visible']) )
            ? 
            '<div class="block-icon pngfix"></div><h2 class="block-title">' . $block['subject'] . '</h2>'
            :
            '') 
         . '<div class="content">' . $block['content'] . '</div>
      </section>';
  }
}


/**
 * Returns a content of a block wrapped in proper divs.
 */
function gv_blocks_getBlockThemed($block_data)
{
  $block = module_invoke($block_data['module'], 'block_view', $block_data['delta']);
  if ($block) {
    return gv_blocks_wrapInBlockThemed($block_data, $block);
  }
  return NULL;
}


/**
 * Returns a content of a block Get access to the VoIP footprint... Banner.
 */
function gv_blocks_get_accessToFootprintBanner() {
  return '<div class="link">' . l(t('Learn more'), '<front>') . '</div>';
}


/**
 * Block Request a quote with a multistep form.
 */
function gv_blocks_get_requestQuote() {

  drupal_add_library('system', 'ui.core');
  drupal_add_library('system', 'ui.widget');
  drupal_add_library('system', 'ui.position');  

  //drupal_add_library('system', 'effects.bounce');
  
  $path_to_custom_js = drupal_get_path('module', 'gv_blocks') . '/js/';
  drupal_add_js($path_to_custom_js . 'gv_requestquote.js');
  $path_to_custom_js = 'sites/all/modules/_JS/multipart_form/';
  drupal_add_js($path_to_custom_js . 'jquery.form.js');
  drupal_add_js($path_to_custom_js . 'jquery.validate.js');
  //drupal_add_js($path_to_custom_js . 'bbq.js');
  drupal_add_js($path_to_custom_js . 'jquery.form.wizard-min.js');
  
  $token = md5(time()); //drupal_get_token('test');
  $_SESSION['requestQuoteToken'] = $token;

  $out = '
   <div id="requestQuoteFormWrapper">
        <div class="sending results" style="display: none;"></div>
        <div class="success results" style="display: none;"></div>
        <div class="fail results" style="display: none;">The Request has failed! <br>Something went wrong. <br>Please, contact the site administrator.</div>
        
        <form class="multipartForm bbq" method="post" action="/request" style="height: 272px; overflow: hidden;">

                
                <div id="fieldWrapper">
                    
                    <div class="step" id="phones_amt_section"> 
                        
                            <div class="question">' . t('How many phones do you have?') . '</div>
                            
                            <input type="radio" name="phones_amt" value="1 - 2" /><div class="label_after">1 - 2</div>
                            <input type="radio" name="phones_amt" value="3 - 5" /><div class="label_after">3 - 5</div>
                            <input type="radio" name="phones_amt" value="6 - 10" /><div class="label_after">6 - 10</div>
                            <input type="radio" name="phones_amt" value="11 - 20" /><div class="label_after">11 - 20</div>
                            <input type="radio" name="phones_amt" value="21 - 50" /><div class="label_after">21 - 50</div>
                            <input type="radio" name="phones_amt" value="50+" /><div class="last_radio label_after">50+</div>
                            
                            <div class="step-notice">' . t('Step <span class="f">!first</span>of<span class="s">!second</span>', array('!first' => 1, '!second' => 5)) . '</div>
                    </div>
                    
                    <div class="step" id="q_for">
                        
                            <div class="question">' . t('You are looking for a quote for...') . '</div>
                            
                            <input type="radio" name="q_for" value="Home" /><div class="label_after">' . t('Home') .'</div>
                            <input type="radio" name="q_for" value="Home-based Business" /><div class="label_after">' . t('Home-based Business') . '</div>
                            <input type="radio" name="q_for" value="Business" /><div class="last_radio label_after">' . t('Business') . '</div>
                         
                            <div class="step-notice">' . t('Step <span class="f">!first</span>of<span class="s">!second</span>', array('!first' => 2, '!second' => 5)) . '</div>
                    </div>
                    

                    <div class="step" id="buying_time">
                        
                            <div class="question">' . t('What is your buying time frame?') . '</div>
                            
                            <input type="radio" name="buying_time" value="ASAP" /><div class="label_after">' . t('ASAP') . '</div>
                            <input type="radio" name="buying_time" value="Less Than 1 Month" /><div class="label_after">' . t('Less Than 1 Month') . '</div>
                            <input type="radio" name="buying_time" value="1 - 3 Months" /><div class="label_after">' . t('1 - 3 Months') . '</div>
                            <input type="radio" name="buying_time" value="3 - 6 Months" /><div class="label_after">' . t('3 - 6 Months') . '</div>
                            <input type="radio" name="buying_time" value="More Than 6 Months" /><div class="last_radio label_after">' . t('More Than 6 Months') . '</div>
                         
                            <div class="step-notice">' . t('Step <span class="f">!first</span>of<span class="s">!second</span>', array('!first' => 3, '!second' => 5)) . '</div>
                    </div>
                    

                    <div class="step" id="connection">
                        
                            <div class="question">' . t('What is your data connection?') . '</div>
                            
                            <input type="radio" name="connection" value="DSL" /><div class="label_after">' . t('DSL') . '</div>
                            <input type="radio" name="connection" value="Cable" /><div class="label_after">' . t('Cable') . '</div>
                            <input type="radio" name="connection" value="T1" /><div class="label_after">' . t('T1') . '</div>
                            <input type="radio" name="connection" value="Fiber" /><div class="label_after">' . t('Fiber') . '</div>
                            <input type="radio" name="connection" value="Other" /><div class="label_after">' . t('Other') . '</div>
                            <input type="radio" name="connection" value="Need New Connection" /><div class="last_radio label_after">' . t('Need New Connection') . '</div>
                              
                            <div class="step-notice">' . t('Step <span class="f">!first</span>of<span class="s">!second</span>', array('!first' => 4, '!second' => 5)) . '</div>
                    </div>
                    
                    
                    <div class="step" id="personal_info">
                        
                            <div class="question">' . t('Fill out the form below:') . '</div>
                            
                            <div class="label_before required">' . t('First Name') . '<span class="form-required">*</span></div>
                                <input class="after required name" name="firstname" id="firstname" />
                            <div class="label_before required">' . t('Last Name') . '<span class="form-required">*</span></div>
                                <input class="after required" name="lastname" id="lastname" />
                                
                            <div class="label_before required">' . t('Company') . '</div>
                                <input class="after" name="company" id="company" />
                                
                            <div class="label_before required">' . t('Email') . '<span class="form-required">*</span></div>
                                <input class="after email required" name="email" id="email" />
                                
                            <div class="label_before required">' . t('Phone') . '</div>
                                <input class="after required phone" name="phone_1" id="phone_1" value="" />
                                <input class="after required phone" name="phone_2" id="phone_2" value="" />
                                <input class="after required phone" name="phone_3" id="phone_3" value="" />
                                
                            <div class="label_before">' . t('Notes') . '</div>
                                <input class="after" name="notes" id="notes" />
                         
                           <div class="step-notice">' . t('Step <span class="f">!first</span>of<span class="s">!second</span>', array('!first' => 5, '!second' => 5)) . '</div>
                             
                    </div>
                    
                </div>
            
                <div id="Navigation"> 							
                        <input class="navigation_button" id="back" value="Back" type="reset" />
                        <input class="navigation_button" id="next" value="Next" type="submit" />
                </div>
                
                <input type="hidden" name="token" value="' . $token . '" />
                <input type="hidden" name="source" value="block" />
        </form>

        <p id="data"></p>
</div>
<div class="block_footer"></div>
  ';
  
  return $out;
}


/**
 * Block Request a quote with a multistep form FOR PAGE v1 - /request-voip-phone-system-quote.
 */
function gv_blocks_get_requestQuoteForPage() {

  drupal_add_library('system', 'ui.widget');

  //drupal_add_library('system', 'effects.bounce');
  
  $path_to_custom_js = 'sites/all/modules/_JS/multipart_form/';
  drupal_add_js($path_to_custom_js . 'jquery.form.js');
  drupal_add_js($path_to_custom_js . 'jquery.validate.js');
  //drupal_add_js($path_to_custom_js . 'bbq.js');
  drupal_add_js($path_to_custom_js . 'jquery.form.wizard-min.js');
  
  drupal_add_library('system', 'ui.core');
  drupal_add_library('system', 'ui.widget');
  drupal_add_library('system', 'ui.position');  
  
  drupal_add_js('sites/all/libraries/jquery.plugins/ui/jquery.ui.selectmenu.js');
  drupal_add_css('sites/all/libraries/jquery.plugins/ui/themes/base/jquery.ui.selectmenu.css');
  
  $path_to_custom_js = drupal_get_path('module', 'gv_blocks') . '/js/';
  drupal_add_js($path_to_custom_js . 'gv_requestquote_page.js');
  
  
  $token = md5(time()); //drupal_get_token('test');
  $_SESSION['requestQuoteToken'] = $token;
  
  $out = '
   <div id="requestQuoteFormWrapper">
        <div class="sending results" style="display: none;"></div>
        <div class="success results" style="display: none;"></div>
        <div class="fail results" style="display: none;">The Request has failed! <br>Something went wrong. <br>Please, contact the site administrator.</div>
        
        <form class="multipartForm bbq" method="post" action="/request" style="height: 300px; overflow: hidden;">

                
                <div id="fieldWrapper">
                    
                    <div class="step" id="phones_amt_section">
                        
                            <div class="question">' . t('How many phones do you need?') . '<span class="form-required">*</span></div>
                              <select name="phones_amt" id="phones_amt" class="input required">
                                <!--<option value="">- Select a value -</option>-->
                                <option value="1 - 4">1 - 4</option>
                                <option selected="selected" value="5 - 10">5 - 10</option>
                                <option value="11 - 20">11 - 20</option>
                                <option value="21 - 50">21 - 50</option>
                                <option value="More than 50">More than 50</option>
                              </select>
                            
                            
                            <div class="question">' . t('What is your current phone needs?') . '<span class="form-required">*</span></div>
                              <select name="q_for" id="q_for" class="input required">
                                <!--<option value="">- Select a value -</option>-->
                                <option value="Replace current phone system">' . t('Replace current phone system') .'</option>
                                <option value="Need a phone system for a new office">' . t('Need a phone system for a new office') .'</option>
                                <option value="Expand on our current phone system">' . t('Expand on our current phone system') .'</option>
                              </select>

                            <div class="question">' . t('What type of quote do you need?') . '<span class="form-required">*</span></div>
                              <select name="q_type" id="q_type" class="input required">
                                <!--<option value="">- Select a value -</option>-->
                                <option value="Both phones and service">' . t('Both phones and service') .'</option>
                                <option value="Phone system only">' . t('Phone system only') .'</option>
                                <option value="Service provider only">' . t('Service provider only') .'</option>
                              </select>
                            
                            <div class="question">' . t('What is your buying time frame?') . '<span class="form-required">*</span></div>
                              <select name="buying_time" id="buying_time" class="input required">
                                <!--<option value="">- Select a value -</option>-->
                                <option value="ASAP">' . t('ASAP') .'</option>
                                <option value="1-3 Months">' . t('1-3 Months') .'</option>
                                <option value="3-6 Months">' . t('3-6 Months') .'</option>
                              </select>
                            
                            <div id="on_error"></div>
                            
                            <!--<div class="step-notice">' . t('Step <span class="f">!first</span>of<span class="s">!second</span>', array('!first' => 1, '!second' => 2)) . '</div> -->
                    </div>
                    
                    <div class="step" id="personal_info">
                        
                            <div class="question">' . t('Fill out the form below:') . '</div>
                            
                            <div class="wrapper">
                              <div class="label_before required">' . t('First Name') . '<span class="form-required">*</span></div>
                                <input class="after required name" name="firstname" id="firstname" />
                            </div>
                            
                            <div class="wrapper">
                              <div class="label_before required">' . t('Last Name') . '<span class="form-required">*</span></div>
                                <input class="after required" name="lastname" id="lastname" />
                            </div>
                            
                            <div class="wrapper">
                              <div class="label_before required">' . t('Company') . '</div>
                                <input class="after" name="company" id="company" />
                            </div>

                            <div class="wrapper">
                              <div class="label_before required">' . t('Email') . '<span class="form-required">*</span></div>
                                <input class="after email required" name="email" id="email" />
                            </div>
                            
                            <div class="wrapper">
                              <div class="label_before">' . t('Website') . '</div>
                                <input class="after" name="website" id="website" />
                            </div>
                            
                            <div class="wrapper">
                              <div class="label_before required">' . t('Phone') . '<span class="form-required">*</span></div>
                              <div id="phone">
                                <input class="after required phone" name="phone_1" id="phone_1" value="" />
                                <input class="after required phone" name="phone_2" id="phone_2" value="" />
                                <input class="after required phone" name="phone_3" id="phone_3" value="" />
                               </div>
                            </div>
                         
                           <!--<div class="step-notice">' . t('Step <span class="f">!first</span>of<span class="s">!second</span>', array('!first' => 2, '!second' => 2)) . '</div>-->
                           <div class="protected"></div>
                    </div>
                    
                </div>
            
                <div id="Navigation"> 							
                        <input class="navigation_button" id="back" value="Back" type="reset" />
                        <input class="navigation_button" id="next" value="Next" type="submit" />
                </div>
                
                <input type="hidden" name="token" value="' . $token . '" />
                <input type="hidden" name="source" value="page" />
                <input type="hidden" name="version" value="1" />
                
        </form>

        <p id="data"></p>
</div>
<div class="block_footer"></div>
  ';
  
  return $out;
}


/**
 * Block Request a quote with a multistep form FOR PAGE v2 - /voip-provider-quotes.
 */
function gv_blocks_get_requestQuoteForPage_v2() {

  $path_to_custom_js = 'sites/all/modules/_JS/multipart_form/';
  drupal_add_js($path_to_custom_js . 'jquery.form.js');
  drupal_add_js($path_to_custom_js . 'jquery.validate.js');
  //drupal_add_js($path_to_custom_js . 'bbq.js');
  drupal_add_js($path_to_custom_js . 'jquery.form.wizard-min.js');
  
  drupal_add_js('sites/all/libraries/jquery.plugins/jquery.hint-with-password.js');
  
  drupal_add_library('system', 'ui.core');
  drupal_add_library('system', 'ui.widget');
  drupal_add_library('system', 'ui.position');  
  
  $path_to_custom_js = drupal_get_path('module', 'gv_blocks') . '/js/';
  drupal_add_js($path_to_custom_js . 'gv_requestquote_page_v2.js');
  
  
  $token = md5(time()); //drupal_get_token('test');
  $_SESSION['requestQuoteToken'] = $token;
  
  $out = '
   <div id="requestQuoteFormWrapper">
        <div class="sending results" style="display: none;"></div>
        <div class="success results" style="display: none;"></div>
        <div class="fail results" style="display: none;">The Request has failed! <br>Something went wrong. <br>Please, contact the site administrator.</div>
        
        <form class="multipartForm bbq" method="post" action="/request">

                
                <div id="fieldWrapper">
                    
                    <div class="step" id="questions_section">

                            <div class="question">' . t('How many phones do you need?') . '<span class="form-required">*</span></div>
                            <div class="subset first">
                              <input type="radio" name="phones_amt" value="1 - 4" /><div class="label_after">1 - 4</div>
                              <input type="radio" name="phones_amt" value="11 - 20" /><div class="last_radio label_after">11 - 20</div>
                            </div>
                            <div class="subset second">
                              <input checked type="radio" name="phones_amt" value="5 - 10" /><div class="label_after">5 - 10</div>
                              <input type="radio" name="phones_amt" value="more than 20" /><div class="last_radio label_after">more than 20</div>
                            </div>
                            
                            <div class="bottom-clear"></div>


                            <div class="question">' . t('What type of quote do you need?') . '<span class="form-required">*</span></div>
                            <div class="subset first">
                              <input type="radio" name="q_type" value="Phone system only" /><div class="label_after">' . t('Phone system only') . '</div>
                              <input checked type="radio" name="q_type" value="Both phones and service" /><div class="label_after">' . t('Both phones and service') . '</div>
                            </div>
                            <div class="subset second">
                              <input type="radio" name="q_type" value="Service provider only" /><div class="last_radio label_after">' . t('Service provider only') . '</div>
                            </div>

                            <div class="question">' . t('What is your buying time frame?') . '<span class="form-required">*</span></div>
                            <div class="subset first">
                              <input checked type="radio" name="buying_time" value="ASAP" /><div class="label_after">' . t('ASAP') . '</div>
                              <input type="radio" name="buying_time" value="3 - 6 Months" /><div class="last_radio label_after">' . t('3 - 6 Months') . '</div>
                            </div>  
                            <div class="subset second">
                              <input type="radio" name="buying_time" value="1 - 3 Months" /><div class="label_after">' . t('1 - 3 Months') . '</div>
                            </div>
                            
                            <div class="bottom-clear"></div>
                            
                            <div class="subset-name"> 
                              <div class="wrapper subset first">
                                <div class="label_before required">' . t('Name') . '<span class="form-required">*</span></div>
                                  <input class="after required name" name="firstname" id="firstname" title="First" />
                              </div>

                              <div class="wrapper subset second">
                                  <input class="after required" name="lastname" id="lastname" title="Last" />
                              </div>
                            </div>
                            
                            <div class="bottom-clear"></div>
                            
                            <div class="wrapper">
                              <div class="label_before required">' . t('Email') . '<span class="form-required">*</span></div>
                                <input class="after email required" name="email" id="email" title="Enter a valid email" />
                            </div>
                         
                            <div class="wrapper">
                              <div class="label_before required">' . t('Phone') . '<span class="form-required">*</span></div>
                              <div id="phone">
                                <input class="after required phone" name="phone_1" id="phone_1" value="" />
                                <input class="after required phone" name="phone_2" id="phone_2" value="" />
                                <input class="after required phone" name="phone_3" id="phone_3" value="" />
                               </div>
                            </div>
                            
                            <div class="wrapper">
                              <div class="label_before">' . t('Company') . '</div>
                                <input class="after" name="company" id="company" title="Optional" />
                            </div>

   
                     

                            <div id="on_error"></div>

                            <!--<div class="step-notice">' . t('Step <span class="f">!first</span>of<span class="s">!second</span>', array('!first' => 1, '!second' => 2)) . '</div> -->
                    </div>

                    <div class="protected"></div>
                
                </div>
                
                
            
                <div id="Navigation"> 							
                        <input class="navigation_button" id="back" value="Back" type="reset" />
                        <input class="navigation_button" id="next" value="Next" type="submit" />
                </div>
                
                <input type="hidden" name="token" value="' . $token . '" />
                <input type="hidden" name="source" value="page" />
                <input type="hidden" name="version" value="2" />
                
        </form>

        <p id="data"></p>
</div>
<div class="block_footer"></div>
  ';
  
  return $out;
}



/**
 * Block Request a quote with a multistep form FOR PAGE v2 - /voip-provider-quotes.
 */
function gv_blocks_get_requestQuoteForPage_v3() {

  $path_to_custom_js = 'sites/all/modules/_JS/multipart_form/';
  drupal_add_js($path_to_custom_js . 'jquery.form.js');
  drupal_add_js($path_to_custom_js . 'jquery.validate.js');
  //drupal_add_js($path_to_custom_js . 'bbq.js');
  drupal_add_js($path_to_custom_js . 'jquery.form.wizard-min.js');
  
  drupal_add_js('sites/all/libraries/jquery.plugins/jquery.hint-with-password.js');

  drupal_add_library('system', 'ui.core');
  drupal_add_library('system', 'ui.widget');
  drupal_add_library('system', 'ui.position');  
  
  $path_to_custom_js = drupal_get_path('module', 'gv_blocks') . '/js/';
  drupal_add_js($path_to_custom_js . 'gv_requestquote_page_v2.js');
  
  drupal_add_js($path_to_custom_js . 'gv_brandsCarousel.js');
  drupal_add_js('sites/all/libraries/jquery.plugins/jcarousel/jquery.jcarousel.min.js');
  drupal_add_css('sites/all/libraries/jquery.plugins/jcarousel/skins/tango/skin.css');
  
  
  $token = md5(time()); //drupal_get_token('test');
  $_SESSION['requestQuoteToken'] = $token;
  
  $out = '
   <div id="requestQuoteFormWrapper">
        <div class="sending results" style="display: none;"></div>
        <div class="success results" style="display: none;"></div>
        <div class="fail results" style="display: none;">The Request has failed! <br>Something went wrong. <br>Please, contact the site administrator.</div>
        
        <form class="multipartForm bbq" method="post" action="/request">

                
                <div id="fieldWrapper">
                    
                    <div class="step" id="questions_section">

                            <div class="question">' . t('Amount of phones needed') . ':</div>
                              <select name="phones_amt" id="phones_amt" class="input required">
                                <option value="1 - 4">1 - 4</option>
                                <option selected="selected" value="5 - 10">5 - 10</option>
                                <option value="11 - 20">11 - 20</option>
                                <option value="21 - 50">21 - 50</option>
                                <option value="More than 50">More than 50</option>
                              </select>
           
                            <div class="question">' . t('VoIP Service desired') . ':</div>
                              <select name="q_type" id="q_type" class="input required">
                                <option value="Both phones and service">' . t('Both phones and service') .'</option>
                                <option value="Phone system only">' . t('Phone system only') .'</option>
                                <option value="Service provider only">' . t('Service provider only') .'</option>
                              </select>
                            
                            <div class="question">' . t('Buying time frame') . ':</div>
                              <select name="buying_time" id="buying_time" class="input required">
                                <!--<option value="">- Select a value -</option>-->
                                <option value="ASAP">' . t('ASAP') .'</option>
                                <option value="1-3 Months">' . t('1-3 Months') .'</option>
                                <option value="3-6 Months">' . t('3-6 Months') .'</option>
                              </select>
                              
                            
                            <div class="bottom-clear"></div>


                            <div class="wrapper">
                              <div class="label_before required">' . t('First Name') . ':<span class="form-required">*</span></div>
                                <input class="after required firstname" name="firstname" id="firstname" />
                            </div>
                            
                            <div class="wrapper">
                              <div class="label_before required">' . t('Last Name') . ':<span class="form-required">*</span></div>
                                <input class="after required lastname" name="lastname" id="lastname" />
                            </div>
                            
                            <div class="wrapper">
                              <div class="label_before required">' . t('Email') . ':<span class="form-required">*</span></div>
                                <input class="after email required" name="email" id="email" />
                            </div>
                         
                            <div class="wrapper phone">
                              <div class="label_before required">' . t('Phone') . ':<span class="form-required">*</span></div>
                                <input class="after required phone" name="phone" id="phone" value="" />
                            </div>

                            <div class="wrapper company">
                              <div class="label_before">' . t('Company') . ':</div>
                                <input class="after" name="company" id="company" />
                            </div>

                            <div class="wrapper website">
                              <div class="label_before">' . t('Website') . ':</div>
                                <input class="after" name="website" id="website" />
                            </div>
                            
                            <div id="on_error"></div>

                            <!--<div class="step-notice">' . t('Step <span class="f">!first</span>of<span class="s">!second</span>', array('!first' => 1, '!second' => 2)) . '</div> -->
                                
                            <div class="protected"></div>
                    </div>

                    
                
                </div>
                
                
            
                <div id="Navigation"> 							
                        <input class="navigation_button" id="back" value="Back" type="reset" />
                        <input class="navigation_button" id="next" value="Next" type="submit" />
                </div>
                
                
                <input type="hidden" name="token" value="' . $token . '" />
                <input type="hidden" name="source" value="page" />
                <input type="hidden" name="version" value="3" />
                
        </form>

        <p id="data"></p>
</div>
<div class="block_footer"></div>
  ';
  
  return $out;
}